02-Functions-homeworks
urakymzhan/fulls-sep-21-workshop pull request #3
Opened 2021-10-17 20:55 UTC by Sarinza

2021-10-18 16:32 UTC, urakymzhan requested changes

2021-10-18 16:32 UTC, urakymzhan commented on 02-functions/02-default-greet/default-greet.js
> +    if(lastName === null || lastName === ''){
Instead of checking if else here.
Maybe you want to use default params: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

2021-10-18 16:32 UTC, urakymzhan commented on 02-functions/03-tax-calculator/tax-calculator.js
> +      console.loconsole.log('Please submit proper price: ');
typo

2021-10-18 16:32 UTC, urakymzhan commented on 02-functions/03-tax-calculator/tax-calculator.js
> +      console.loconsole.log('Please submit proper price: ');
```
// We will assume price is always numeric value
const states = {
  'NY': 0.04,
  'NJ': 0.0625,
  'IL': 0.09,
  'CA': 0.10,
  'TX': 0.08,
}

function taxCalculator(price, state) {
  // IDEAL SOLUTION
  var afterTaxesTotal = 0;
  if(states.hasOwnProperty(state)) {
    for(let key in states) {
        if(key === state) {
          afterTaxesTotal = price + (price*states[key])
        } 
      }
  } else {
    return 'Incorrect State';
  }
  return afterTaxesTotal;    
 }

 var taxes = taxCalculator(10, 'TX');
 console.log(taxes); 
```

2021-10-18 16:32 UTC, urakymzhan commented on 02-functions/04-my-mnemonic/my-mnemonic.js
> +    const arr1 = [...otherStrings];
You don't have to store array again inside array

2021-10-18 16:32 UTC, urakymzhan commented on 02-functions/04-my-mnemonic/my-mnemonic.js
> +          const fisrtCharacter = arr1[i].charAt(0);
Instead of `arr1[i].charAt(0)` just `arr1[i][0]` maybe

2021-10-18 16:32 UTC, urakymzhan commented on 02-functions/04-my-mnemonic/my-mnemonic.js
> +        else {
No need for continue

2021-10-18 16:32 UTC, urakymzhan commented on 02-functions/04-my-mnemonic/my-mnemonic.js
> +console.log(mnemonic)
Ideally this problem requires to use `arr1[i][0.toUpperCase()`  method

2021-10-26 19:41 UTC, Sarinza commented on 02-functions/02-default-greet/default-greet.js
> +    if(lastName === null || lastName === ''){
updated with default params

2021-10-26 19:45 UTC, Sarinza commented on 02-functions/03-tax-calculator/tax-calculator.js
> +      console.loconsole.log('Please submit proper price: ');
updated

2021-10-26 19:49 UTC, Sarinza commented on 02-functions/04-my-mnemonic/my-mnemonic.js
> +    const arr1 = [...otherStrings];
updated

2021-10-26 19:50 UTC, Sarinza commented on 02-functions/04-my-mnemonic/my-mnemonic.js
> +          const fisrtCharacter = arr1[i].charAt(0);
updated to [0]

2021-10-26 19:50 UTC, Sarinza commented on 02-functions/04-my-mnemonic/my-mnemonic.js
> +        else {
removed continue else block

2021-10-26 19:57 UTC, Sarinza commented on 02-functions/04-my-mnemonic/my-mnemonic.js
> +console.log(mnemonic)
added toUpperCase() method

2021-10-26 21:36 UTC, merged